CREATE DATABASE SHAREDGOLD_AI
FROM SHARE MBRXEHU.YPB38047.airbnb_gold_share;

-- Copy shared gold tables into AIRBNB_INVESTMENT_DB.GOLD
CREATE OR REPLACE TABLE AIRBNB_INVESTMENT_DB.GOLD.AI_OUTPUTS AS
SELECT * FROM SHAREDGOLD_AI.GOLD.AI_OUTPUTS;

CREATE OR REPLACE TABLE AIRBNB_INVESTMENT_DB.GOLD.BOROUGH_SUMMARY AS
SELECT * FROM SHAREDGOLD_AI.GOLD.BOROUGH_SUMMARY;

CREATE OR REPLACE TABLE AIRBNB_INVESTMENT_DB.GOLD.INVESTMENT_SCORES AS
SELECT * FROM SHAREDGOLD_AI.GOLD.INVESTMENT_SCORES;

CREATE OR REPLACE TABLE AIRBNB_INVESTMENT_DB.GOLD.REVIEW_THEMES AS
SELECT * FROM SHAREDGOLD_AI.GOLD.REVIEW_THEMES;

-----------
-- AWS INTEGRATION

SHOW INTEGRATIONS;

DESCRIBE INTEGRATION AIRBNB_S3_INT;