-- Creates the PROPERTY_TYPE_CACHE table storing on-demand AI property-type recommendations generated by property_type_helper.
-- Co-authored with CoCo
--
-- Standard UPPERCASE columns. The helper writes via a parameterized INSERT
-- (only INSERT privilege required), matching the other *_CACHE tables.

CREATE OR REPLACE TABLE AIRBNB_INVESTMENT_DB.GOLD.PROPERTY_TYPE_CACHE (
    CITY                   VARCHAR,
    NEIGHBOURHOOD_CLEANSED VARCHAR,
    PERSONA                VARCHAR,
    OUTPUT_TYPE            VARCHAR,
    INVESTMENT_SCORE       FLOAT,
    AI_NARRATIVE           VARCHAR,
    CONFIDENCE             VARCHAR,
    METRICS_JSON           VARCHAR,
    PROMPT_VERSION         VARCHAR,
    MODEL_USED             VARCHAR,
    COMPUTED_AT            TIMESTAMP_NTZ
);
