-- Creates the PROPERTY_TYPE_CACHE table storing on-demand AI property-type recommendations generated by property_type_helper.
-- Co-authored with CoCo
--
-- Columns are quoted lowercase to match the pandas frame written by
-- write_to_cache() via Snowpark write_pandas (quote_identifiers=True), mirroring
-- the existing AI_OUTPUTS layout.

CREATE TABLE IF NOT EXISTS AIRBNB_INVESTMENT_DB.GOLD.PROPERTY_TYPE_CACHE (
    "city"                   VARCHAR,
    "neighbourhood_cleansed" VARCHAR,
    "persona"                VARCHAR,
    "output_type"            VARCHAR,
    "investment_score"       FLOAT,
    "ai_narrative"           VARCHAR,
    "confidence"             VARCHAR,
    "metrics_json"           VARCHAR,
    "prompt_version"         VARCHAR,
    "model_used"             VARCHAR,
    "computed_at"            TIMESTAMP_NTZ
);
